object Extra {
    const val EXTRA_RESTAURANT_NAME = "EXTRA_RESTAURANT_NAME"
    const val EXTRA_RESTAURANT_IMAGE = "EXTRA_RESTAURANT_IMAGE"
    const val EXTRA_RESTAURANT_DESCRIPTION = "EXTRA_RESTAURANT_DESCRIPTION"
    const val EXTRA_RESTAURANT_ADDRESS = "EXTRA_RESTAURANT_ADDRESS"
    const val EXTRA_RESTAURANT_HOURS = "EXTRA_RESTAURANT_HOURS"
}